[build]
  command="ng build"
  publish="dist/angular-quickstart"

[[plugins]]
package = "netlify-build-plugin-pushover"

  [plugins.inputs]
    successMessage = "" #Optional
    errorMessage = "" #Optional

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200